---
name: Andrew
surname: McInerney
position: "Ph.D. Student"
address: "Department of Mathematics and Statistics, University of Limerick"
email: "andrew.mcinerney@ul.ie"
twitter: amcinerney_
github: andrew-mcinerney
linkedin: andrewjmcinerney
date: "`r format(Sys.time(), '%B %Y')`"
fontsize: 11pt
output: 
  vitae::awesomecv
---

```{r setup, include=FALSE}
library(tidyverse)
library(vitae)
knitr::opts_chunk$set(echo = FALSE)
```

# Employment

```{r}
tribble(
  ~ Title, ~ Year, ~ Company, ~ Where, ~ Why,
  "eModerator - Professional Diploma in Data Analytics", "January 2022 - Present", "University of Limerick", "Limerick, Ireland",   
 "Monitored forums and hosted weekly question-and-answer sessions for students in online modules titled `Data Analytics with R' and `Introduction to Predictive Analytics'.",
 
 "eModerator - Professional Diploma in Data Analytics", "January 2022 - Present", "University of Limerick", "Limerick, Ireland",   
 "Prepared tutorial and computer-laboratory sheets for `Introduction to Predictive Analytics'.",
 
 "Tutor - Department of Mathematics and Statistics", "September 2020 - Present", "", "",  "Tutored undergraduate and postgraduate students in the following modules: Advanced Data Analysis, Applied Business Statistics, Applied Data Analysis, Statistics for Data Analytics, Stochastic Processes.",
 
 "Tutor - Department of Mathematics and Statistics", "September 2020 - Present", "", "",
 "Graded undergraduate and postgraduate assignments in addition to final examinations.",


 "Data Sciene Intern", "June 2021 - September 2021", "Hertz", "Dublin, Ireland", 
 "Performed cluster analysis on customer and rental data to provide meaningful customer segments for the Marketing team.",
 
 
 "Data Analytics Intern", "January 2019 - August 2019", "Regeneron Pharmaceuticals", "Limerick, Ireland",
 "Undertook an eight-month internship within the Process Monitoring and Data Analytics team.",
 
 "Data Analytics Intern", "January 2019 - August 2019", "Regeneron Pharmaceuticals", "Limerick, Ireland",
 "Main responsibilities included carrying out ad hoc statistical analyses (e.g., t-tests and ANOVA), statistical process control (SPC), and design of experiments (DOE)."
	              
) %>% 
  detailed_entries(Title, Year, Company, Where, Why, .protect = T)
```


# Education

```{r}
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where, ~ Why,
  "PhD~in Statistics (SFI Centre for Research Training in Foundations of Data Science)", "2020 - Present", "University of Limerick", "Dublin, Ireland",
  "Title: `A Statistical Approach to Neural Networks' (Supervisor: Dr.~Kevin Burke).",
  "BSc~in Mathematical Sciences (First Class Honours)", "2016 - 2020", "University of Limerick", "Limerick, Ireland", NA
  
) %>% 
  detailed_entries(Degree, Year, Institution, why = Why)
```


# Technical Skills

## Programming
\vspace{-0.2cm}
- 6 years experience with R:
    - Developed R packages during PhD: [**selectnn**](https://github.com/andrew-mcinerney/selectnn), [**statnnet**](https://github.com/andrew-mcinerney/statnnet).
    - Taught R to undergraduate and postgraduate students.
- Proficient in: SPSS, JMP, \LaTeX.
- Familiar with: AWS, Git, Python, SQL, Tableau.

# Publications

## Preprints

```{r preprints}
tribble(
  ~ when, ~ title, ~ details, ~ where, ~ url,
  "2022", "A Statistically-Based Approach to Feedforward Neural Network Model Selection", 
  "\\textbf{McInerney, A.}, Burke, K.",  "arXiv preprint", "https://arxiv.org/abs/2207.04248",
) %>%
  brief_entries(glue::glue("<details>, \\href{<url>}{\\textbf{<title>}} (\\textit{<where>})", .open = "<", .close = ">"), when, .protect = FALSE)
```

\newpage

# Presentations

## Invited

```{r invited pres}
tribble(
  ~ when, ~ title, ~ details, ~ where, 
  "2022", "Feedforward Neural Networks as Statistical Models", 
  "Invited Speaker",  "The 3rd Young Statisticians’ Section of the Irish Statistical Association (Young-ISA) Meeting: Collaborative Workflow in Data Science",
  
  "2022", "Variable and Architecture Selection in Neural Networks", 
  "Invited Speaker",  "The 5th International Conference on Econometrics and Statistics (EcoSta 2022)",
  
  "2021", "Information-criteria-based Model Selection for Neural Networks", 
  "Invited Speaker",  "The Royal Statistical Society International Conference 2021 (RSS)",
) %>%
  brief_entries(glue::glue("\\textbf{<title>}, <where>", .open = "<", .close = ">"), when, .protect = FALSE)
```



## Contributed

```{r presentaions}
tribble(
  ~ when, ~ title, ~ details, ~ where, 
  "2022", "Statistical information-criteria-based neural network input and hidden node selection", 
  "Contributed Presentation",  "36th International Workshop on Statistical Modelling (IWSM 2022)",
  
  "2022", "A Statistical Approach to Neural Network Model Selection", 
  "Contributed Presentation",  "The 42nd Conference on Applied Statistics in Ireland (CASI 2022)",
  
  "2021", "Information-criteria-based Model Selection for Neural Networks", 
  "Contributed Presentation",  "The 44th Research Students' Conference in Probability and Statistics (RSC 2021)",
  
  "2021", "Information-criteria-based Model Selection for Neural Networks", 
  "Contributed Presentation",  "The 4th International Conference on Econometrics and Statistics (EcoSta 2021)",
) %>%
  brief_entries(glue::glue("{\\textbf{<title>}}, <where>", .open = "<", .close = ">"), when, .protect = FALSE)
```


# Awards

```{r awards}
tribble(
  ~ when, ~ what,
  "2021", "RSC 2021 - `Best Long Talk'",
) %>%
  brief_entries(glue::glue("<what>", .open = "<", .close = ">"), when, .protect = FALSE)
```

# Volunteering

```{r}
tribble(
  ~ Title, ~ Year, ~ Company, ~ Where, ~ Why,
  "Treasurer", "September 2021 - Present", "UL SIAM Student Chapter (Society for Industrial and Applied Mathematics)", "Limerick, Ireland",   
 "Secured funding for the chapter from Analog Devices.",
 
 "Treasurer", "September 2021 - Present", "UL SIAM Student Chapter (Society for Industrial and Applied Mathematics)", "Limerick, Ireland",   
 "Organised the 8th Annual Irish SIAM Student Conference."
 
) %>% 
  detailed_entries(Title, Year, Company, Where, Why, .protect = T)
```

